#CCE_Board_Definitions:

COINES_INSTALL_PATH ?= ../../../..

EXAMPLE_FILE ?= write_read_register_data.c

SHUTTLE_BOARD ?= NONE

override TARGET=PC

include $(COINES_INSTALL_PATH)/coines.mk
