COINES_INSTALL_PATH ?= ../../

EXAMPLE_FILE ?= app_switch.c

override TARGET=PC
override COINES_BACKEND=COINES_LEGACY

INCLUDEPATHS += \
$(COINES_INSTALL_PATH)/coines-api/pc \
$(COINES_INSTALL_PATH)/coines-api/pc/comm_driver \
$(COINES_INSTALL_PATH)/coines-api/pc/comm_intf \

include $(COINES_INSTALL_PATH)/coines.mk