COINES_INSTALL_PATH ?= ../../..

EXAMPLE_FILE ?= external_temp.c

LIBRARY_LOCATION ?= $(COINES_INSTALL_PATH)/libraries/ext_temperature

C_SRCS += \
$(LIBRARY_LOCATION)/ext_temperature.c

INCLUDEPATHS += \
$(LIBRARY_LOCATION) \
$(COINES_INSTALL_PATH)/coines-api/common

include $(COINES_INSTALL_PATH)/coines.mk