name: mkdocs-deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material mkdocs-with-pdf mkdocs-drawio-exporter
      - name: Install Draw.io Desktop
        run: |
             set -euo pipefail
   
             drawio_arch=amd64
             drawio_version=18.1.3
             drawio_sha256sum=39a50f25ad52d6909c5c18d89a7cfc193e8e31fb98458a390c0a0709d22e9e10
   
             drawio_deb="drawio-${drawio_arch}-${drawio_version}.deb"
             drawio_url="https://github.com/jgraph/drawio-desktop/releases/download/v${drawio_version}/${drawio_deb}"
   
             curl -L -o "$drawio_deb" "$drawio_url"
             sha256sum --check <<<"${drawio_sha256sum}  $drawio_deb"
             sudo apt-get install -y libasound2 xvfb ./"$drawio_deb"
      - name: Fetch Assets
        run: |
             mkdir -p doc/docs/assets/fonts
             wget -O doc/docs/assets/fonts/boschsans_regular.woff2 https://www.bosch-sensortec.com/media/tech/fonts/woff2/boschsans_regular.woff2
             wget -O doc/docs/assets/fonts/boschsans_bold.woff2 https://www.bosch-sensortec.com/media/tech/fonts/woff2/boschsans_bold.woff2
             wget -O doc/docs/assets/favicon.ico https://www.bosch-sensortec.com/media/tech/tech_images/favicon.ico
             wget -O doc/docs/assets/supergraphic.svg https://www.bosch-presse.de/pressportal/de/media/res/gfx/supergraphic.svg
             wget -O doc/docs/assets/logo.svg https://www.bosch-presse.de/pressportal/de/media/res/gfx/bosch-invented-for-life.svg
      - name: Build and publish
        run: |
              xvfb-run -a mkdocs gh-deploy --force --config-file doc/mkdocs.yml
